### ISSUE TITLE
Document `asynchronous_invocation` use

### ISSUE THREAD

**Issue by dmcmorris** [openfaas/kafka-connector#58]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

By default the connector does not do async invocations, however searching through the code it will do so if the `asynchronous_invocation` environment variable is set to true

## Expected Behaviour

The default behaviour as well as the existence of this environment variable should be documented as most topic/queue operators are by nature async.

## Current Behaviour

No documentation of the option currently exists.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

When using OpenFaas for long running functions, async invocation is ideal so that you can still properly limit non-async requests.  When using the kafka-connector this means it needs to be configured to trigger the async endpoint.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Sounds good, feel free to raise a PR.

**Comment by alexellis** [comment]
This has now been documented and I've also added it to the chart as an option as it didn't seem to be there.
