### ISSUE TITLE
Capacity levels?

### ISSUE THREAD

**Issue by alexandery** [openfaas/kafka-connector#60]
I'm trying to understand how many Kafka topics can be monitored by the connector. Would it support thousands of topics being monitored? 

I know for sure that many Kafka libraries cannot listen to a large number of partitions, so I'm concerned with the level of capacity Kafka connector in OpenFaaS provides.

Would appreciate any insight - whether such investigation has been done or not, anything helps. Thanks!

P.S. I was unable to find anything relevant on this in my research.

**Comment by alexellis** [comment]
How many do you need?

I'll close this issue out for the time being as it seems old. I would also encourage you to use the templates for any issues you want to raise in the future.
