### ISSUE TITLE
pass multiple topics to connector

### ISSUE THREAD

**Issue by JasonPad19** [openfaas/kafka-connector#61]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I try to pass multiple topics to connector. but it give me a parsing error.

## Expected Behaviour
I should be able to pass multiple topics to connector.

## Current Behaviour
After i run this, I got an parsing error -  topic2 can't end with ,

helm upgrade kafka-connector openfaas/kafka-connector \
    --install \
    --namespace openfaas \
    --set gateway_url="..." \
    --set broker_host="..." \
    --set topics="CommandQueue,topic2,topic3" \
    --set print_response="true" \
    --set print_response_body="true" 

## Possible Solution
What i did to work around it is to pass one topic in the helm upgrade, and then kubectl edit the yaml by replacing CommandQueue  with CommandQueue,topic2,topic3. 
So that connector can listen to multiple topics.

## Steps to Reproduce (for bugs)

1. run helm upgrade with parameter
2.
3.
4.

## Context

pass multiple topics to connector 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
You need to use a comma separated list. I am not sure what you're doing differently to our blog post? ://www.openfaas.com/blog/kafka-connector/

If someone lands here and can reproduce the issue, we would like to see this written up with an example.
